import React, { ReactElement } from 'react';
import { get } from 'lodash';
import { Tag, Tooltip } from '@chakra-ui/react';
import * as Interfaces from 'src/backend/controllers/utils/interfaces';
import SuggestionSourceEnum from 'src/backend/shared/constants/SuggestionSourceEnum';

const sourceFieldConfig = {
  [SuggestionSourceEnum.COMMUNITY]: {
    badge: 'Nkọwa okwu',
    description: 'This suggestion came from a user on Nkọwa okwu',
    color: 'purple',
  },
  [SuggestionSourceEnum.IGBO_SPEECH]: {
    badge: 'IgboSpeech',
    description:
      'This suggestion came from a user on IgboSpeech. All Igbo from IgboSpeech is generated by the IgboSpeech ML',
    color: 'blue',
  },
  [SuggestionSourceEnum.IGBO_WIKIMEDIANS]: {
    badge: 'Igbo Wikimedians',
    description: 'This suggestion came from Igbo Wikimedians Group',
    color: 'green',
  },
  [SuggestionSourceEnum.BBC]: {
    badge: 'BBC Igbo News',
    description: 'This suggestion came from BBC Igbo News articles',
    color: 'orange',
  },
  [SuggestionSourceEnum.INTERNAL]: {
    badge: 'Igbo API Editor Platform',
    description: 'This suggestion came from the internal Igbo API Editor Platform',
    color: 'gray',
  },
};

const OriginField = ({
  record,
  source,
}: {
  label?: string;
  record?: Interfaces.WordData;
  source: string;
}): ReactElement => {
  const value = get(record, source) || SuggestionSourceEnum.INTERNAL;
  const badgeLabel = sourceFieldConfig[value].badge || sourceFieldConfig[SuggestionSourceEnum.INTERNAL].badge;
  const label = sourceFieldConfig[value].description || sourceFieldConfig[SuggestionSourceEnum.INTERNAL].description;
  const colorScheme = sourceFieldConfig[value].color || sourceFieldConfig[SuggestionSourceEnum.INTERNAL].color;

  return (
    <Tooltip label={label}>
      <Tag
        cursor="default"
        variant="outline"
        colorScheme={colorScheme}
        borderRadius="full"
        backgroundColor={`${colorScheme}.50`}
        whiteSpace="nowrap"
      >
        {badgeLabel}
      </Tag>
    </Tooltip>
  );
};

export default OriginField;
