import React, { ReactElement } from 'react';
import { get } from 'lodash';
import { Badge, Tooltip } from '@chakra-ui/react';
import * as Interfaces from 'src/backend/controllers/utils/interfaces';
import SuggestionSourceEnum from 'src/backend/shared/constants/SuggestionSourceEnum';

const sourceFieldConfig = {
  [SuggestionSourceEnum.COMMUNITY]: {
    badge: 'Nkọwa okwu',
    description: 'This suggestion came from a user on Nkọwa okwu',
    color: 'purple',
  },
  [SuggestionSourceEnum.IGBO_SPEECH]: {
    badge: 'IgboSpeech',
    description:
      'This suggestion came from a user on IgboSpeech. All Igbo from IgboSpeech is generated by the IgboSpeech ML.',
    color: 'blue',
  },
  [SuggestionSourceEnum.INTERNAL]: {
    badge: 'Igbo API Editor',
    description: 'This suggestion came from the internal Igbo API Editor Platform',
    color: 'gray',
  },
};

const SourceField = ({
  record,
  source,
}: {
  label?: string;
  record?: Interfaces.WordData;
  source: string;
}): ReactElement => {
  const value = get(record, source);
  const badgeLabel = sourceFieldConfig[value].badge || sourceFieldConfig[SuggestionSourceEnum.INTERNAL].badge;
  const label = sourceFieldConfig[value].description || sourceFieldConfig[SuggestionSourceEnum.INTERNAL].description;
  const colorScheme = sourceFieldConfig[value].color || sourceFieldConfig[SuggestionSourceEnum.INTERNAL].color;

  return (
    <Tooltip label={label}>
      <Badge cursor="default" variant="outline" colorScheme={colorScheme}>
        {badgeLabel}
      </Badge>
    </Tooltip>
  );
};

SourceField.defaultProps = {
  record: { id: null },
};

export default SourceField;
