export default {
  'auth/account-exists-with-different-credential': 'Account exists with different credentials',
  'auth/auth-domain-config-required': 'The domain must be configured',
  'auth/cancelled-popup-request': null,
  'auth/operation-not-allowed': 'Operation not allowed',
  'auth/operation-not-supported-in-this-environment': 'Unsupported operation',
  'auth/popup-blocked': 'Unable to open sign up window',
  'auth/popup-closed-by-user': null,
  'auth/unauthorized-domain': 'Unauthorized domain',
  'auth/user-not-found': "User doesn't exist",
  'auth/user-disabled': 'User has been deactivated',
  'auth/expired-action-code': 'Session timeout. Please try again',
  'auth/weak-password': 'Weak password',
  'auth/email-already-in-use': 'Email is already in use',
  'auth/invalid-phone-number': 'Invalid phone. Please try again',
  'auth/invalid-verification-code': 'Incorrect code. Please try again',
  'auth/missing-verification-code': 'No code provided. Please try again',
};
