enum CrowdsourcingType {
  INPUT_IGBO_DEFINITION = 'INPUT_IGBO_DEFINITION',
  REVIEW_IGBO_DEFINITION = 'REVIEW_IGBO_DEFINITION',
  RECORD_EXAMPLE_AUDIO = 'RECORD_EXAMPLE_AUDIO',
  VERIFY_EXAMPLE_AUDIO = 'VERIFY_EXAMPLE_AUDIO',
  VERIFY_EXAMPLE_TEXT = 'VERIFY_EXAMPLE_TEXT',
  TRANSLATE_IGBO_SENTENCE = 'TRANSLATE_IGBO_SENTENCE',
}

export default CrowdsourcingType;
