enum EntityStatus {
  UNSPECIFIED = 'UNSPECIFIED',
  INACTIVE = 'INACTIVE',
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  PAUSED = 'PAUSED',
  DELETED = 'DELETED',
}

export default EntityStatus;
