enum Tense {
  INFINITIVE = 'INFINITIVE',
  IMPERATIVE = 'IMPERATIVE',
  SIMPLE_PAST = 'SIMPLE_PAST',
  PRESENT_PASSIVE = 'PRESENT_PASSIVE',
  SIMPLE_PRESENT = 'SIMPLE_PRESENT',
  PRESENT_CONTINUOUS = 'PRESENT_CONTINUOUS',
  FUTURE = 'FUTURE',
}

export default Tense;
